# Generated by Django 5.2.8 on 2025-11-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'رزرو', 'verbose_name_plural': 'رزروها'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'دکتر', 'verbose_name_plural': 'دکترها'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'امتیاز', 'verbose_name_plural': 'امتیازها'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'نوبت', 'verbose_name_plural': 'نوبت ها'},
        ),
    ]
